# -*- coding: utf-8 -*-
"""Untitled7.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mbj39vew38yQlU5zhc_0lf2T1GTZRfo7
"""

!pip install streamlit pymongo pandas pyngrok

# Commented out IPython magic to ensure Python compatibility.
# %%writefile app.py
# 
# #importar librerias
# import streamlit as st
# from pymongo import MongoClient
# import pandas as pd
# 
# # CONEXION A MONGODB ATLAS
# # IMPORTANT: Replace 'YOUR_MONGODB_PASSWORD' with your actual MongoDB Atlas password.
# # For better security, consider using Streamlit secrets (st.secrets) or environment variables.
# URI = "mongodb+srv://Rodrix09:ALPHA_R0m30@cluster0.ulnmym5.mongodb.net/?appName=Cluster0"
# @st.cache_resource
# def init_connection():
#     return MongoClient(URI)
# 
# try:
#     Cliente = init_connection()
#     db = Cliente["GaleriaArte"]
#     Obras = db["Obras"]
#     Autores = db["Autores"]
#     Registros = db["Registros"]
# 
# except Exception as e:
#     st.error(f"Error al conectar con MongoDB: {e}")
# 
# # CONFIGURACION STREAMLIT
# 
# st.set_page_config(
#     page_title="Galería de Arte",
#     layout="wide"
# )
# 
# st.title("🎨 Sistema Galería de Arte")
# 
# st.write(
#     "Administración de Obras, Autores y Registros"
# )
# 
# # TABS
# 
# tab_ver, tab_autores, tab_registros, tab_agregar, tab_editar, tab_eliminar = st.tabs([
#     "🎨 Ver Obras",
#     "👨‍🎨 Autores",
#     "📋 Registros",
#     "➕ Agregar",
#     "✏️ Editar",
#     "❌ Eliminar"
# ])
# 
# # TAB VER OBRAS
# 
# with tab_ver:
#     st.header("Listado de Obras")
# 
#     documentos = list(Obras.find())
# 
#     if documentos:
# 
#         df = pd.DataFrame(documentos)
# 
#         col1,col2,col3 = st.columns(3)
# 
#         col1.metric(
#             "Total de Obras",
#             len(df)
#         )
# 
#         col2.metric(
#             "Valor Promedio",
#             f"${df['valor_estimado'].mean():,.0f}"
#         )
# 
#         col3.metric(
#             "Autores Diferentes",
#             df["autor_id"].nunique()
#         )
# 
#         st.markdown("---")
# 
#         st.subheader("Obras por Tipo")
# 
#         st.bar_chart(
#             df["tipo"].value_counts()
#         )
# 
#         st.subheader("Obras por Estado")
# 
#         st.bar_chart(
#             df["estado"].value_counts()
#         )
# 
#         st.subheader("Tabla de Obras")
# 
#         st.dataframe(df)
# 
#     else:
#         st.info("No existen obras registradas")
# 
# # TAB AUTORES
# 
# with tab_autores:
#     st.header("Listado de Autores")
# 
#     documentos = list(Autores.find())
# 
#     if documentos:
# 
#         df = pd.DataFrame(documentos)
# 
#         st.subheader("Autores por Especialidad")
# 
#         st.bar_chart(
#             df["especialidad"].value_counts()
#         )
# 
#         st.subheader("Autores Reconocidos")
# 
#         st.bar_chart(
#             df["reconocido"].value_counts()
#         )
# 
#         st.dataframe(df)
# 
#     else:
#         st.info("No existen autores")
# 
# # TAB REGISTROS
# 
# with tab_registros:
#     st.header("Historial de Registros")
# 
#     documentos = list(Registros.find())
# 
#     if documentos:
# 
#         df = pd.DataFrame(documentos)
# 
#         st.subheader("Registros por Prioridad")
# 
#         st.bar_chart(
#             df["prioridad"].value_counts()
#         )
# 
#         st.dataframe(df)
# 
#     else:
#         st.info("No existen registros")
# 
# # TAB AGREGAR
# 
# with tab_agregar:
#     st.header("Registrar Nueva Obra")
# 
#     with st.form("form_crear"):
# 
#         id_obra = st.number_input(
#             "ID",
#             min_value=1,
#             step=1
#         )
# 
#         titulo = st.text_input(
#             "Título"
#         )
# 
#         tipo = st.selectbox(
#             "Tipo",
#             [
#                 "Pintura",
#                 "Escultura",
#                 "Fotografia",
#                 "Arte Digital"
#             ]
#         )
# 
#         anio = st.number_input(
#             "Año",
#             min_value=1900,
#             max_value=2030
#         )
# 
#         valor = st.number_input(
#             "Valor Estimado",
#             min_value=0
#         )
# 
#         estado = st.selectbox(
#             "Estado",
#             [
#                 "Excelente",
#                 "Bueno",
#                 "Regular"
#             ]
#         )
# 
#         autor_id = st.number_input(
#             "ID Autor",
#             min_value=1
#         )
# 
#         ubicacion = st.text_input(
#             "Ubicación"
#         )
# 
#         guardar = st.form_submit_button(
#             "Guardar Obra"
#         )
# 
#         if guardar:
# 
#             nueva_obra = {
# 
#                 "_id": int(id_obra),
#                 "titulo": titulo,
#                 "tipo": tipo,
#                 "año": int(anio),
#                 "valor_estimado": int(valor),
#                 "estado": estado,
#                 "autor_id": int(autor_id),
#                 "ubicacion": ubicacion
# 
#             }
# 
#             Obras.insert_one(nueva_obra)
# 
#             st.success(
#                 "✅ Obra agregada correctamente"
#             )
# 
#             st.rerun()
# 
# 
# # TAB EDITAR
# 
# with tab_editar:
#     documentos = list(Obras.find())
# 
#     if documentos:
# 
#         opciones = {
#             f"{doc['titulo']} (ID {doc['_id']})": doc
#             for doc in documentos
#         }
# 
#         seleccion = st.selectbox(
#             "Selecciona una obra",
#             opciones.keys()
#         )
# 
#         obra_actual = opciones[seleccion]
# 
#         with st.form("form_editar"):
# 
#             titulo = st.text_input(
#                 "Título",
#                 value=obra_actual["titulo"]
#             )
# 
#             valor = st.number_input(
#                 "Valor",
#                 value=int(
#                     obra_actual["valor_estimado"]
#                 )
#             )
# 
#             estado = st.selectbox(
#                 "Estado",
#                 ["Excelente","Bueno","Regular"]
#             )
# 
#             ubicacion = st.text_input(
#                 "Ubicación",
#                 value=obra_actual["ubicacion"]
#             )
# 
#             actualizar = st.form_submit_button(
#                 "Actualizar"
#             )
# 
#             if actualizar:
# 
#                 Obras.update_one(
#                     {"_id": obra_actual["_id"]},
#                     {
#                         "$set": {
#                             "titulo": titulo,
#                             "valor_estimado": valor,
#                             "estado": estado,
#                             "ubicacion": ubicacion
#                         }
#                     }
#                 )
# 
#                 st.success(
#                     "✏️ Obra actualizada"
#                 )
# 
#                 st.rerun()
# 
#     else:
#         st.info(
#             "No hay obras para editar"
#         )
# 
# # TAB ELIMINAR
# with tab_eliminar:
#     documentos = list(Obras.find())
# 
#     if documentos:
# 
#         opciones = {
#             f"{doc['titulo']} (ID {doc['_id']})": doc
#             for doc in documentos
#         }
# 
#         seleccion = st.selectbox(
#             "Selecciona la obra",
#             opciones.keys()
#         )
# 
#         obra_actual = opciones[seleccion]
# 
#         if st.button(
#             "Eliminar Obra"
#         ):
# 
#             Obras.delete_one(
#                 {"_id": obra_actual["_id"]}
#             )
# 
#             st.success(
#                 "❌ Obra eliminada"
#             )
# 
#             st.rerun()
# 
#     else:
#         st.info(
#             "No hay obras para eliminar"
#         )

!pip install pyngrok # Asegura que pyngrok esté instalado
import subprocess
from pyngrok import ngrok, conf
from google.colab import userdata

# Terminar cualquier túnel ngrok existente para evitar el límite de túneles en la capa gratuita.
print("Terminando cualquier túnel ngrok existente...")
ngrok.kill()

# Obtener el authtoken de ngrok de los secretos de Colab
NGROK_AUTH_TOKEN = userdata.get('NGROK_AUTH_TOKEN')

if not NGROK_AUTH_TOKEN:
    raise ValueError("NGROK_AUTH_TOKEN no encontrado en los secretos de Colab. Por favor, configúrelo.")

# Configurar el authtoken de ngrok
conf.get_default().auth_token = NGROK_AUTH_TOKEN

# Ejecutar Streamlit en segundo plano
print("Iniciando la aplicación Streamlit en segundo plano...")
process = subprocess.Popen(["python", "-m", "streamlit", "run", "app.py"], stdout=subprocess.PIPE, stderr=subprocess.PIPE)

# Esperar a que Streamlit se inicie y mostrar su URL local (opcional, para depuración)
# Es posible que necesites ajustar la duración del tiempo de espera o usar comprobaciones más robustas
import time
time.sleep(5)

# Crear un túnel ngrok al puerto predeterminado de la aplicación Streamlit (8501)
public_url = ngrok.connect(8501)
print(f"\nTu aplicación Streamlit está activa en: {public_url}")

# Para detener el túnel ngrok y el proceso de Streamlit, descomente y ejecute esta celda.
ngrok.kill()
if 'process' in locals() and process.poll() is None: # Comprobar si el proceso sigue en ejecución
    process.terminate()
    print("Aplicación Streamlit terminada.")
print("Túnel ngrok y proceso de Streamlit detenidos.")